[package]
name = "dibs-query-syntax"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
description = "Snark parser and source AST for the Dibs PostgreSQL query language"
license = "MIT OR Apache-2.0"
build = "build.rs"

[dependencies]
snark.workspace = true
facet.workspace = true

margin.workspace = true

[dev-dependencies]
margin-term.workspace = true

[build-dependencies]
snark-dsl = { workspace = true, features = ["typed-ast"] }
snark = { workspace = true }
