// Rust-facing names and leaf decoding for the single structural Dibs/PostgreSQL AST.
ast({
  declaration_identifier: { decode: "text" },
  result_mode: { decode: "text" },

  _statement: { enum: "Statement" },
  _relation: { enum: "Relation" },
  _expr: { enum: "Expression" },
  _or_expr: { enum: "OrExpression" },
  _and_expr: { enum: "AndExpression" },
  _not_expr: { enum: "NotExpression" },
  _predicate_expr: { enum: "PredicateExpression" },
  _generic_expr: { enum: "GenericExpression" },
  _additive_expr: { enum: "AdditiveExpression" },
  _multiplicative_expr: { enum: "MultiplicativeExpression" },
  _exponent_expr: { enum: "ExponentExpression" },
  _unary_expr: { enum: "UnaryExpression" },
  _postfix_expr: { enum: "PostfixExpression" },
  _atom_expr: { enum: "AtomExpression" },
  _special_form_expr: { enum: "SpecialFormExpression" },
  _b_expr: { enum: "BExpression" },

  with_statement: { as: "With" },
  select_statement: { as: "Select" },
  table_statement: { as: "TableQuery" },
  insert_query_source: { as: "Query", fields: { body: { enum: "InsertQueryBody" } } },
  set_operation: { fields: { operator: { enum: "SetOperator" } } },
  select_core: { fields: { body: { enum: "SelectBody" } } },
  distinct_select: { as: "Distinct", fields: { value: { enum: "DistinctSelectKind" } } },
  distinct_on_select: { as: "On" },
  plain_distinct_select: { as: "Plain" },
  ordinary_select: { as: "Ordinary", fields: { value: { enum: "OrdinarySelectKind" } } },
  all_select: { as: "All" },
  unqualified_select: { as: "Unqualified" },
  select_set_expression: { fields: { value: { enum: "SelectSetNode" } } },
  select_target: { fields: { value: { enum: "SelectTargetValue" } } },
  grouping_element: { fields: { value: { enum: "GroupingElementValue" } } },
  insert_value: { fields: { value: { enum: "InsertValueNode" } } },
  insert_source: { fields: { value: { enum: "InsertSourceNode" } } },
  conflict_target: { fields: { value: { enum: "ConflictTargetNode" } } },
  conflict_action: { fields: { value: { enum: "ConflictActionNode" } } },
  in_rhs: { fields: { value: { enum: "InRhsValue" } } },
  array_expr: { as: "Array", fields: { statement: { enum: "ArrayQuery" } } },
  limit_clause: { fields: { value: { enum: "LimitValue" } } },
  assignment: { fields: { value: { enum: "AssignmentValue" } } },
  quantified_comparison_expr: { as: "QuantifiedComparison", fields: { right: { enum: "QuantifiedRight" } } },
  value_postfix_operation: { fields: { value: { enum: "ValuePostfixOperationNode" } } },
  window_suffix: { fields: { window: { enum: "WindowReference" } } },
  interval_literal: { as: "Interval", fields: { value: { enum: "IntervalValue" } } },
  values_statement: { as: "Values" },
  insert_target: { struct: "InsertTarget" },
  insert_alias: { struct: "InsertAlias" },
  insert_statement: { as: "Insert" },
  update_statement: { as: "Update" },
  delete_statement: { as: "Delete" },

  joined_relation: { as: "Join" },
  relation_primary: { fields: { value: { enum: "RelationPrimaryValue" } } },
  table_relation: { as: "Table" },
  derived_relation: { as: "Derived" },
  function_relation: { as: "Function" },
  parenthesized_relation: { as: "Parenthesized" },

  or_expr: { as: "Or" },
  and_expr: { as: "And" },
  not_expr: { as: "Not" },
  is_predicate_expr: { as: "IsPredicate", fields: { test: { enum: "IsPredicateTestNode" } } },
  is_value_test: { as: "Value" },
  is_distinct_test: { as: "DistinctFrom" },
  between_expr: { as: "Between" },
  in_expr: { as: "In" },
  binary_expr: { as: "Binary", fields: { operator: { enum: "BinaryOperator" } } },
  b_binary_expr: { as: "Binary", fields: { operator: { enum: "BBinaryOperator" } } },
  unary_expr: { as: "Unary" },
  b_unary_expr: { as: "Unary" },
  value_postfix_expr: { as: "Postfix" },
  callable_window_expr: { as: "Window", fields: { expression: { enum: "WindowFunction" } } },
  cast_expr: { as: "Cast" },
  at_time_zone_expr: { as: "AtTimeZone" },
  call_expr: { as: "Call" },
  trim_expr: { as: "Trim" },
  case_expr: { as: "Case" },
  coalesce_expr: { as: "Coalesce" },
  nullif_expr: { as: "NullIf" },
  greatest_expr: { as: "Greatest" },
  least_expr: { as: "Least" },
  extract_expr: { as: "Extract" },
  position_expr: { as: "Position" },
  substring_expr: { as: "Substring" },
  overlay_expr: { as: "Overlay" },
  exists_expr: { as: "Exists" },
  row_expr: { as: "Row" },
  parenthesized_expr: { as: "Parenthesized", fields: { value: { enum: "ParenthesizedValue" } } },
  parenthesized_subquery: { as: "Subquery" },
  parenthesized_scalar: { as: "Scalar" },
  parenthesized_row: { as: "RowValue" },
  qualified_name_expr: { as: "Name" },
  current_value_expr: { as: "CurrentValue", decode: "text" },

  named_bind: { as: "NamedBind", decode: "text" },
  escaped_string_literal: { as: "EscapedStringLiteral", decode: "text" },
  unicode_string_literal: { as: "UnicodeStringLiteral", decode: "text" },
  bit_string_literal: { as: "BitStringLiteral", decode: "text" },
  hex_string_literal: { as: "HexStringLiteral", decode: "text" },
  string_literal: { as: "StringLiteral", decode: "text" },
  dollar_quoted_literal: { as: "DollarQuotedLiteral", decode: "text" },
  numeric_literal: { as: "NumericLiteral", decode: "text" },
  boolean_literal: { as: "BooleanLiteral", decode: "text" },
  null_literal: { as: "NullLiteral" },

  wildcard_target: { as: "Wildcard" },
  qualified_wildcard_target: { as: "QualifiedWildcard" },
  expression_target: { as: "Expression" },

  grouping_expression: { as: "Expression" },
  empty_grouping_set: { as: "Empty" },
  grouping_tuple: { as: "Tuple" },
  rollup_clause: { as: "Rollup" },
  cube_clause: { as: "Cube" },
  grouping_sets_clause: { as: "GroupingSets" },

  qualified_name: { struct: "QualifiedName" },
  identifier: { as: "Identifier", decode: "text" },
  union_except_operator: { as: "UnionOrExcept", decode: "text" },
  intersect_operator: { as: "Intersect", decode: "text" },
  additive_operator: { as: "Additive", decode: "text" },
  multiplicative_operator: { as: "Multiplicative", decode: "text" },
  exponent_operator: { as: "Exponent" },
  unary_operator: { decode: "text" },
  quoted_identifier: { as: "QuotedIdentifier", decode: "text" },
  comparison_operator: { as: "Comparison", decode: "text" },
  generic_operator: { as: "Generic", decode: "text" },
  operator_name: { decode: "text" },
  frame_mode: { decode: "text" },
  frame_exclusion: { fields: { kind: { enum: "FrameExclusionKind" } } },
  frame_exclusion_kind: { enum: "FrameExclusionKind" },
  lock_wait_policy: { decode: "text" },
  materialization_clause: { decode: "text" },
  set_quantifier: { decode: "text" },
  extract_field: { decode: "text" },
  interval_field: { decode: "text" },
  normal_form: { decode: "text" },
  all_literal: { decode: "text" },
  default_literal: { decode: "text" },
});
