ast({
  declaration_identifier: { decode: "text" },
  result_mode: { decode: "text" },

  _statement_item: { enum: "StatementNode" },
  named_bind: { as: "NamedBind", decode: "text" },
  escaped_string_literal: { as: "EscapedStringLiteral", decode: "text" },
  unicode_string_literal: { as: "UnicodeStringLiteral", decode: "text" },
  bit_string_literal: { as: "BitStringLiteral", decode: "text" },
  hex_string_literal: { as: "HexStringLiteral", decode: "text" },
  string_literal: { as: "StringLiteral", decode: "text" },
  dollar_quoted_literal: { as: "DollarQuotedLiteral", decode: "text" },
  quoted_identifier: { as: "QuotedIdentifier", decode: "text" },
  numeric_literal: { as: "NumericLiteral", decode: "text" },
  boolean_literal: { as: "BooleanLiteral", decode: "text" },
  null_literal: { as: "NullLiteral" },
  identifier: { as: "Identifier", decode: "text" },
  colon_operator: { as: "ColonOperator", decode: "text" },
  statement_symbol: { as: "Symbol", decode: "text" },
});
