// Rust-facing names and leaf decoding for the single structural Dibs/PostgreSQL AST.
ast({
  declaration_identifier: { decode: "text" },
  result_mode: { decode: "text" },

  _statement: { enum: "Statement" },
  _relation: { enum: "Relation" },
  _expr: { enum: "Expression" },
  _atom_expr: { enum: "AtomExpression" },

  with_statement: { as: "With" },
  select_statement: { as: "Select" },
  set_operation: { fields: { operator: { enum: "SetOperator" } } },
  select_set_expression: { fields: { value: { enum: "SelectSetNode" } } },
  select_quantifier: { fields: { expression: { enum: "SelectQuantifierExpression" } } },
  select_target: { fields: { value: { enum: "SelectTargetValue" } } },
  grouping_element: { fields: { value: { enum: "GroupingElementValue" } } },
  insert_value: { fields: { value: { enum: "InsertValueNode" } } },
  insert_source: { fields: { value: { enum: "InsertSourceNode" } } },
  conflict_target: { fields: { value: { enum: "ConflictTargetNode" } } },
  conflict_action: { fields: { value: { enum: "ConflictActionNode" } } },
  in_rhs: { fields: { value: { enum: "InRhsValue" } } },
  window_expr: { as: "Window", fields: { expression: { enum: "WindowFunction" }, window: { enum: "WindowReference" } } },
  array_expr: { as: "Array", fields: { statement: { enum: "ArrayQuery" } } },
  limit_clause: { fields: { value: { enum: "LimitValue" } } },
  assignment: { fields: { value: { enum: "AssignmentValue" } } },
  quantified_comparison_expr: { as: "QuantifiedComparison", fields: { right: { enum: "QuantifiedRight" } } },
  postfix_operation: { fields: { value: { enum: "PostfixOperationNode" } } },
  window_suffix: { fields: { window: { enum: "WindowReference" } } },
  interval_literal: { as: "Interval", fields: { value: { enum: "IntervalValue" } } },
  values_statement: { as: "Values" },
  insert_statement: { as: "Insert" },
  update_statement: { as: "Update" },
  delete_statement: { as: "Delete" },

  joined_relation: { as: "Join" },
  relation_primary: { fields: { value: { enum: "RelationPrimaryValue" } } },
  table_relation: { as: "Table" },
  derived_relation: { as: "Derived" },
  function_relation: { as: "Function" },
  parenthesized_relation: { as: "Parenthesized" },

  or_expr: { as: "Or" },
  and_expr: { as: "And" },
  not_expr: { as: "Not" },
  is_test_expr: { as: "IsTest" },
  distinct_test_expr: { as: "DistinctTest" },
  between_expr: { as: "Between" },
  in_expr: { as: "In" },
  like_expr: { as: "Like" },
  binary_expr: { as: "Binary", fields: { operator: { enum: "BinaryOperator" } } },
  unary_expr: { as: "Unary" },
  cast_expr: { as: "Cast" },
  collate_expr: { as: "Collate" },
  at_time_zone_expr: { as: "AtTimeZone" },
  subscript_expr: { as: "Subscript" },
  field_access_expr: { as: "FieldAccess" },
  aggregate_call: { as: "Aggregate" },
  function_call: { as: "Call" },
  case_expr: { as: "Case" },
  coalesce_expr: { as: "Coalesce" },
  nullif_expr: { as: "NullIf" },
  greatest_expr: { as: "Greatest" },
  least_expr: { as: "Least" },
  extract_expr: { as: "Extract" },
  position_expr: { as: "Position" },
  substring_expr: { as: "Substring" },
  overlay_expr: { as: "Overlay" },
  exists_expr: { as: "Exists" },
  scalar_subquery_expr: { as: "ScalarSubquery" },
  row_expr: { as: "Row" },
  parenthesized_expr: { as: "Parenthesized" },
  qualified_name_expr: { as: "Name" },
  current_value_expr: { as: "CurrentValue", decode: "text" },

  named_bind: { as: "NamedBind", decode: "text" },
  escaped_string_literal: { as: "EscapedStringLiteral", decode: "text" },
  unicode_string_literal: { as: "UnicodeStringLiteral", decode: "text" },
  bit_string_literal: { as: "BitStringLiteral", decode: "text" },
  hex_string_literal: { as: "HexStringLiteral", decode: "text" },
  string_literal: { as: "StringLiteral", decode: "text" },
  dollar_quoted_literal: { as: "DollarQuotedLiteral", decode: "text" },
  numeric_literal: { as: "NumericLiteral", decode: "text" },
  boolean_literal: { as: "BooleanLiteral", decode: "text" },
  null_literal: { as: "NullLiteral" },

  wildcard_target: { as: "Wildcard" },
  qualified_wildcard_target: { as: "QualifiedWildcard" },
  expression_target: { as: "Expression" },

  grouping_expression: { as: "Expression" },
  empty_grouping_set: { as: "Empty" },
  grouping_tuple: { as: "Tuple" },
  rollup_clause: { as: "Rollup" },
  cube_clause: { as: "Cube" },
  grouping_sets_clause: { as: "GroupingSets" },

  qualified_name: { struct: "QualifiedName" },
  identifier: { as: "Identifier", decode: "text" },
  union_except_operator: { as: "UnionOrExcept", decode: "text" },
  intersect_operator: { as: "Intersect", decode: "text" },
  additive_operator: { as: "Additive", decode: "text" },
  multiplicative_operator: { as: "Multiplicative", decode: "text" },
  exponent_operator: { as: "Exponent" },
  unary_operator: { decode: "text" },
  quoted_identifier: { as: "QuotedIdentifier", decode: "text" },
  comparison_operator: { as: "Comparison", decode: "text" },
  generic_operator: { as: "Generic", decode: "text" },
  operator_name: { decode: "text" },
  frame_mode: { decode: "text" },
  frame_exclusion: { decode: "text" },
  lock_strength: { decode: "text" },
  lock_wait_policy: { decode: "text" },
  materialization_clause: { decode: "text" },
  set_quantifier: { decode: "text" },
  extract_field: { decode: "text" },
  interval_field: { decode: "text" },
  normal_form: { decode: "text" },
  all_literal: { decode: "text" },
  default_literal: { decode: "text" },
});
