[package]
name = "dibs-qgen-generated-api-fixture"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
dibs-runtime = { path = "../../../../dibs-runtime" }
facet = { git = "https://github.com/facet-rs/facet", branch = "deps/align-weavy-for-dibs" }

[build-dependencies]
dibs-pg-catalog = { path = "../../../../dibs-pg-catalog" }
dibs-qgen = { path = "../../.." }
dibs-query-ir = { path = "../../../../dibs-query-ir" }
